export const customerData = [
  {
    bookingId: "1",
    bookingStatus: "PENDING",
    bookingTime: "10:22 am",
    bookingDate: "12/11/2021",
    previousDeals: "12",
    customerName: "Ray Pressley",
    customerLocation: "San Francisco",
    sessionTime: "9:00 am-2:00 pm",
    sessionDate: "Sunday, December22nd, 2019",
    sessionlocation: "50 Hagiwara",
  },
  {
    bookingId: "2",
    bookingStatus: "PENDING",
    bookingTime: "10:22 am",
    bookingDate: "12/11/2021",
    previousDeals: "12",
    customerName: "Andrew Stew",
    customerLocation: "San Francisco",
    sessionTime: "9am-2am",
    sessionDate: "Sunday,December22nd,2019",
    sessionlocation: "50 Hagiwara",
  },

  {
    bookingId: "3",
    bookingStatus: "PENDING",
    bookingTime: "10:22 am",
    bookingDate: "12/11/2021",
    previousDeals: "12",
    customerName: "Henry Spector",
    customerLocation: "San Francisco",
    sessionTime: "9:00 am-2:00 pm",
    sessionDate: "Sunday, December22nd, 2019",
    sessionlocation: "50 Hagiwara",
  },
  {
    bookingId: "4",
    bookingStatus: "PENDING",
    bookingTime: "10:22 am",
    bookingDate: "12/11/2021",
    previousDeals: "12",
    customerName: "Andrew Malik",
    customerLocation: "San Francisco",
    sessionTime: "9am-2am",
    sessionDate: "Sunday,December22nd,2019",
    sessionlocation: "50 Hagiwara",
  },
  {
    bookingId: "5",
    bookingStatus: "PENDING",
    bookingTime: "10:22 am",
    bookingDate: "12/11/2021",
    previousDeals: "12",
    customerName: "Mike Ross",
    customerLocation: "San Francisco",
    sessionTime: "9:00 am-2:00 pm",
    sessionDate: "Sunday, December22nd, 2019",
    sessionlocation: "50 Hagiwara",
  },
  {
    bookingId: "6",
    bookingStatus: "PENDING",
    bookingTime: "10:22 am",
    bookingDate: "12/11/2021",
    previousDeals: "12",
    customerName: "Donna Paulson",
    customerLocation: "San Francisco",
    sessionTime: "9am-2am",
    sessionDate: "Sunday,December22nd,2019",
    sessionlocation: "50 Hagiwara",
  },

  {
    bookingId: "7",
    bookingStatus: "PENDING",
    bookingTime: "10:22 am",
    bookingDate: "12/11/2021",
    previousDeals: "12",
    customerName: "Samantha",
    customerLocation: "San Francisco",
    sessionTime: "9:00 am-2:00 pm",
    sessionDate: "Sunday, December22nd, 2019",
    sessionlocation: "50 Hagiwara",
  },
  {
    bookingId: "8",
    bookingStatus: "PENDING",
    bookingTime: "10:22 am",
    bookingDate: "12/11/2021",
    previousDeals: "12",
    customerName: "Robert Zane",
    customerLocation: "San Francisco",
    sessionTime: "9am-2am",
    sessionDate: "Sunday,December22nd,2019",
    sessionlocation: "50 Hagiwara",
  },
];
